# Application Name
spring.application.name=beans

# Server Port
server.port=8085
job.executor.server-name=SRV_01_01

#hrsd.disability_assessment.url=https://10.196.35.247/hrsd/g2g-services/v1/disability/assessment
hrsd.scholarship.url=http://localhost:3001/scholarship
hrsd.disability_assessment.url=http://localhost:3001/disability
app.entities-config.path=C:/Users/LayanAqel/Documents/entities/entities-config.xml
job.manager.base-url=http://192.168.4.87:8090

logging.level.org.hibernate.engine.jdbc.env.internal=ERROR
logging.level.org.hibernate=ERROR
#spring.jpa.open-in-view=false
# ============================================
# SQL Server Configuration
# ============================================
spring.datasource.url=jdbc:sqlserver://192.168.1.122:1433;databaseName=NRD-EXTERNAL;encrypt=true;trustServerCertificate=true
spring.datasource.username=dev-user
spring.datasource.password=user@321A
##spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BeansDB;encrypt=true;trustServerCertificate=true
#spring.datasource.username=spring_user
#spring.datasource.password=StrongPass#123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============================================
# JPA Configuration (NOT creating tables!)
# ============================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# Config table
# ============================================
config.table.key-column=CONFIG_KEY
config.table.value-column=CONFIG_VALUE
config.table.schema=EXT
config.table.name=JOB_CONFIG
#config.table.key-column=KEY
#config.table.value-column=VALUE
# ============================================
# Logging
# ============================================
logging.level.root=INFO
logging.level.com.example.beans=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

# ============================================
# threading
# ============================================
#how many worker threads to create
job.threads.count=25
#how many BeneficiaryEntity rows to fetch per page
job.db.chunk=25
job.range.chunk=100

job.retry.max-attempts=25
job.retry.delay-ms=2000